FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1
ENV PATH="/app/scripts:${PATH}"

WORKDIR /app
COPY . /app

RUN apk add --update --no-cache gcc libc-dev linux-headers musl-dev mariadb-connector-c-dev openssl-dev libffi-dev
RUN pip install -r requirements.txt

RUN rm -r .dbdata

RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static
RUN adduser -D user
RUN chown -R user:user /vol
RUN chmod -R 755 /vol/web
RUN chown -R user:user wait-for
RUN chmod 755 /app/wait-for
RUN chmod -R 755 /app/scripts
USER user

CMD ["./wait-for", "db:3306", "--", "entrypoint.sh"]