version: '3.8'
services:
    ui:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:8000
        depends_on:
            - "db"
        volumes:
            - .:/app
        environment:
            - DEBUG=1
        command: ["./wait-for", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    redis:
        image: 'redis:alpine'
        restart: always
    db:
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_DATABASE: testrail_import_db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - .dbdata:/var/lib/mysql