version: '3.8'
services:
    ui:
        build:
            context: .
            dockerfile: Dockerfile-deploy
        restart: always
        depends_on:
            - "db"
        volumes:
            - static_data:/vol/web
        environment:
            - SECRET_KEY=${DJANGO_SECRET_KEY}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - CURRENT_HOST=${CURRENT_HOST}
            - TESTRAIL_URL=${TESTRAIL_URL}
            - EVENTSTREAM_ALLOW_ORIGIN=${EVENTSTREAM_ALLOW_ORIGIN}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    proxy:
        build:
            context: ./proxy
        restart: always
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on:
            - ui
    redis:
        image: 'redis:alpine'
        restart: always
    celery-redis:
        image: 'redis:alpine'
        restart: always
    db:
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_DATABASE: testrail_import_db
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - .dbdata:/var/lib/mysql

volumes:
    static_data:
