# Generated by Django 3.2.12 on 2022-04-01 15:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(default=api.models.generate_unique_session_id, max_length=8, unique=True)),
                ('user', models.EmailField(default='trdjadmin@hobbycodes.com', max_length=254)),
                ('id_file_name', models.FileField(upload_to=api.models.upload_to)),
                ('steps_file_name', models.FileField(upload_to=api.models.upload_to)),
                ('attachment_file_name', models.FileField(upload_to=api.models.upload_to)),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=254)),
                ('suite_id', models.IntegerField()),
                ('suite_name', models.CharField(max_length=254)),
                ('section_id', models.IntegerField()),
                ('section_name', models.CharField(max_length=254)),
                ('retry_import', models.BooleanField(default=False)),
                ('total_cases', models.IntegerField()),
                ('imported_cases', models.IntegerField()),
                ('elapsed_time', models.DurationField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
