# Generated by Django 3.2.12 on 2022-04-01 15:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment_file_name',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='task',
            name='elapsed_time',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='imported_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='section_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='section_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='suite_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='suite_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
