# Generated by Django 3.2.12 on 2022-04-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220401_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
