# Generated by Django 3.2.12 on 2022-04-01 19:37

from django.db import migrations, models
import ui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(default=ui.models.generate_unique_session_id, max_length=8, unique=True)),
                ('user', models.EmailField(default='trdjadmin@hobbycodes.com', max_length=254)),
                ('id_file_name', models.FileField(upload_to=ui.models.upload_to)),
                ('steps_file_name', models.FileField(upload_to=ui.models.upload_to)),
                ('attachment_file_name', models.FileField(blank=True, null=True, upload_to=ui.models.upload_to)),
                ('project_id', models.IntegerField(default=0)),
                ('project_name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('suite_id', models.IntegerField(default=0)),
                ('suite_name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('section_id', models.IntegerField(default=0)),
                ('section_name', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('retry_import', models.BooleanField(default=False)),
                ('total_cases', models.IntegerField(default=0)),
                ('imported_cases', models.IntegerField(default=0)),
                ('elapsed_time', models.DurationField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
