# Generated by Django 3.2.12 on 2022-04-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
