# Generated by Django 3.2.12 on 2022-04-01 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_rename_updates_at_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
