# Generated by Django 3.2.12 on 2022-04-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_task_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
