name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Pull main branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: executing remote docker commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        port: ${{ secrets.PORT }}
        script: "cd /app/testrailimport.hobbycodes.com && git pull origin main"
  build:
    needs: deploy
    name: Build Image and Run Container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: executing remote docker commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH2 }}
        port: ${{ secrets.PORT }}
        script: "cd /app/testrailimport.hobbycodes.com && docker-compose -f .\docker-compose-deploy.yml up -d --build"